name: quotes_app
description: Quotes App by M Duta Chandra.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # IMPORTED PACKAGE
  # https://pub.dev/packages/fluro/versions
  fluro: ^2.0.5
  # https://pub.dev/packages/animated_splash_screen/versions
  animated_splash_screen: ^1.3.0
  # https://pub.dev/packages/page_transition/versions
  page_transition: ^2.1.0
  # https://pub.dev/packages/google_fonts/versions
  google_fonts: ^4.0.4
  # https://pub.dev/packages/hive/versions
  hive: ^2.2.3 
  flutter_bloc: ^8.1.3
  # https://pub.dev/packages/get_it/versions
  get_it: ^7.6.0
  # https://pub.dev/packages/equatable/versions
  equatable: ^2.0.5
  # https://pub.dev/packages/internet_connection_checker/versions
  internet_connection_checker: ^1.0.0+1
  # https://pub.dev/packages/dartz/versions
  dartz: ^0.10.1
  # https://pub.dev/packages/dio/versions
  dio: ^5.3.3
  # https://pub.dev/packages/flutter_dotenv/versions
  flutter_dotenv: ^5.1.0
  # https://pub.dev/packages/hive_flutter/versions
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/shimmer_animation/versions
  shimmer_animation: ^2.1.0+1
  # https://pub.dev/packages/intl/versions
  intl: ^0.18.1
  # https://pub.dev/packages/flutter_svg/versions
  flutter_svg: ^1.1.6
  # https://pub.dev/packages/infinite_carousel/versions
  infinite_carousel: ^1.0.2
  # https://pub.dev/packages/auto_size_text/versions
  auto_size_text: ^3.0.0
  # https://pub.dev/packages/home_widget/versions
  home_widget: ^0.4.1
  # https://pub.dev/packages/path_provider/versions
  path_provider: ^2.0.15
  # https://pub.dev/packages/workmanager/versions 
  workmanager: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # https://pub.dev/packages/freezed_annotation/versions
  freezed_annotation: ^2.4.1
  # https://pub.dev/packages/freezed/versions
  freezed: ^2.3.2
  # https://pub.dev/packages/build_runner/versions
  build_runner: ^2.3.3
  # https://pub.dev/packages/json_serializable/versions
  json_serializable: ^6.5.4
  # https://pub.dev/packages/hive_generator/versions
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito_Sans/static/NunitoSans_10pt-Bold.ttf 
    - family: JakartaSans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf 
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/Noto_Serif/static/NotoSerif-SemiBold.ttf 